blank_issues_enabled: false
contact_links:
  - name: Upstream project
    url: https://github.com/Yizuka17/fcitx5-android-personal
    about: Report issues affecting the immediate upstream here when they are not Fcitx17-specific.
